package net.skds.jvk.test;

import net.skds.jvk.annotation.NativeType;
import net.skds.lib2.annotations.AutoGenerated;
import net.skds.lib2.natives.struct.CStruct;
import net.skds.lib2.natives.struct.CStructWrapper;
import net.skds.lib2.natives.struct.WrappedCStruct;

@AutoGenerated
@SuppressWarnings("unused")
public final class TestStruct extends WrappedCStruct {


	public static final CStructWrapper<TestStruct> WRAPPER = new CStructWrapper<>(TestStruct.class);

	/**
	 * values = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO
	 */
	@NativeType("VkStructureType")
	public int sType = 2;

	/**
	 * optional
	 */
	@NativeType("void*")
	public long pNext;

	/**
	 * optional
	 */
	@NativeType("VkDeviceQueueCreateFlags")
	public int flags;

	@NativeType("uint32_t")
	public int queueFamilyIndex;

	@NativeType("uint32_t")
	public int queueCount;

	@NativeType("float*")
	public long pQueuePriorities;

	@Override
	public CStructWrapper<? extends CStruct> getWrapper() {
		return WRAPPER;
	}
}