package net.skds.jvk;

import net.skds.lib2.utils.annotations.AutoGenerated;

@AutoGenerated
@SuppressWarnings("unused")
public final class VkResult {


	/**
	 * Command completed successfully
	 */
	public static final int VK_SUCCESS = 0;

	/**
	 * A fence or query has not yet completed
	 */
	public static final int VK_NOT_READY = 1;

	/**
	 * A wait operation has not completed in the specified time
	 */
	public static final int VK_TIMEOUT = 2;

	/**
	 * An event is signaled
	 */
	public static final int VK_EVENT_SET = 3;

	/**
	 * An event is unsignaled
	 */
	public static final int VK_EVENT_RESET = 4;

	/**
	 * A return array was too small for the result
	 */
	public static final int VK_INCOMPLETE = 5;

	/**
	 * A host memory allocation has failed
	 */
	public static final int VK_ERROR_OUT_OF_HOST_MEMORY = -1;

	/**
	 * A device memory allocation has failed
	 */
	public static final int VK_ERROR_OUT_OF_DEVICE_MEMORY = -2;

	/**
	 * Initialization of an object has failed
	 */
	public static final int VK_ERROR_INITIALIZATION_FAILED = -3;

	/**
	 * The logical device has been lost. See <<devsandqueues-lost-device>>
	 */
	public static final int VK_ERROR_DEVICE_LOST = -4;

	/**
	 * Mapping of a memory object has failed
	 */
	public static final int VK_ERROR_MEMORY_MAP_FAILED = -5;

	/**
	 * Layer specified does not exist
	 */
	public static final int VK_ERROR_LAYER_NOT_PRESENT = -6;

	/**
	 * Extension specified does not exist
	 */
	public static final int VK_ERROR_EXTENSION_NOT_PRESENT = -7;

	/**
	 * Requested feature is not available on this device
	 */
	public static final int VK_ERROR_FEATURE_NOT_PRESENT = -8;

	/**
	 * Unable to find a Vulkan driver
	 */
	public static final int VK_ERROR_INCOMPATIBLE_DRIVER = -9;

	/**
	 * Too many objects of the type have already been created
	 */
	public static final int VK_ERROR_TOO_MANY_OBJECTS = -10;

	/**
	 * Requested format is not supported on this device
	 */
	public static final int VK_ERROR_FORMAT_NOT_SUPPORTED = -11;

	/**
	 * A requested pool allocation has failed due to fragmentation of the pool's memory
	 */
	public static final int VK_ERROR_FRAGMENTED_POOL = -12;

	/**
	 * An unknown error has occurred, due to an implementation or application bug
	 */
	public static final int VK_ERROR_UNKNOWN = -13;

	public static final int VK_ERROR_OUT_OF_POOL_MEMORY = 0;

	public static final int VK_ERROR_INVALID_EXTERNAL_HANDLE = 3;

	public static final int VK_ERROR_FRAGMENTATION = 0;

	public static final int VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS = 0;

	public static final int VK_PIPELINE_COMPILE_REQUIRED = 0;

	public static final int VK_ERROR_SURFACE_LOST_KHR = 0;

	public static final int VK_ERROR_NATIVE_WINDOW_IN_USE_KHR = 1;

	public static final int VK_SUBOPTIMAL_KHR = 3;

	public static final int VK_ERROR_OUT_OF_DATE_KHR = 4;

	public static final int VK_ERROR_INCOMPATIBLE_DISPLAY_KHR = 1;

	public static final int VK_ERROR_VALIDATION_FAILED_EXT = 1;

	public static final int VK_ERROR_INVALID_SHADER_NV = 0;

	public static final int VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT = 0;

	public static final int VK_ERROR_NOT_PERMITTED_KHR = 1;

	public static final int VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT = 0;

	public static final int VK_THREAD_IDLE_KHR = 0;

	public static final int VK_THREAD_DONE_KHR = 1;

	public static final int VK_OPERATION_DEFERRED_KHR = 2;

	public static final int VK_OPERATION_NOT_DEFERRED_KHR = 3;

	public static final int VK_ERROR_COMPRESSION_EXHAUSTED_EXT = 0;

}
